
export const VALUE_DEFINITIONS: Record<string, string> = {
  // Sources
  "Cracking the PM Career": "Book by Jackie Bavaro & Gayle Laakmann McDowell. The definitive guide to PM career progression, interviewing, and day‑to‑day skills.",
  "The Mom Test": "Book by Rob Fitzpatrick. Teaches how to ask questions that avoid biased, useless feedback. Core premise: if they say they’d buy your product but never actually do, you failed the “Mom Test”.",
  "Inspired": "Book by Marty Cagan. The modern bible of product management. Covers empowered product teams and how to build products customers love.",
  "Lenny’s Newsletter": "Substack by Lenny Rachitsky (ex‑Airbnb). Weekly deep‑dives on product strategy, growth tactics, and career advice.",
  "Reforge": "Advanced product growth programs. Known for high‑quality frameworks and real‑world case studies on retention and strategy.",
  "Product School": "Global provider of product management training. Often associated with the “Product Manager Certification” (PMC).",
  "Google Analytics Academy": "Free online courses from Google. Covers data analysis fundamentals and A/B testing experiments.",
  "LinkedIn Learning": "Professional video course library including many specific to product management, Agile, and UX.",
  "Mind the Product": "Global community for product managers. A hub for PM networking and learning.",
  "Stratechery": "Blog by Ben Thompson. Deep analysis of technology strategy and business models.",
  "a16z": "Andreessen Horowitz, a top VC firm. Publishes original research and trend forecasts on various tech sectors.",
  "CB Insights": "Market intelligence platform producing reports on startup funding and emerging technologies.",
  "McKinsey": "Global consulting firm. Publishes data-heavy reports on digital transformation and technology trends.",
  "Gartner": "Research firm famous for the Hype Cycle. Helps PMs understand technology maturity landscapes.",
  "Forrester": "Research firm specialising in customer experience and technology strategy.",
  "earnings calls": "Quarterly public company investor calls revealing executive priorities and competitive commentary.",
  "App Store reviews": "Public user feedback on iOS apps. A goldmine for identifying friction points and delighters.",
  "Reddit": "Social news site with subreddits like r/productmanagement. Offers unfiltered, candid conversations.",
  "TrustRadius": "B2B software review platform. Strong for competitor analysis and switch-reasoning.",
  "G2": "Crowdsourced business software ratings and comparisons. Useful for identifying market positioning.",

  // Frameworks
  "RICE prioritisation": "Prioritisation framework (Reach, Impact, Confidence, Effort). Produces a single score for objective comparison.",
  "RICE": "Prioritisation framework (Reach, Impact, Confidence, Effort). Produces a single score for objective comparison.",
  "Kano Model": "Customer satisfaction framework. Classifies features into Basic, Performance, and Delighters.",
  "JTBD": "Jobs‑To‑Be‑Done. Shifts focus from the product to the progress the user is trying to make.",
  "JTBD analysis": "Analysis using the Jobs-To-Be-Done framework to identify user motivations.",
  "Kano classification": "The process of categorizing features into Kano categories (Basic, Performance, Delighter).",
  "OKRs": "Objectives and Key Results. Goal‑setting framework used for qualitative objectives and quantitative results.",
  "HEART metrics": "UX measurement framework: Happiness, Engagement, Adoption, Retention, Task Success.",
  "HEART framework": "UX measurement framework: Happiness, Engagement, Adoption, Retention, Task Success.",
  "technical debt": "The implied future cost of choosing a quick solution now instead of a more robust one.",
  "unit economics": "Financial metrics (CLTV/CAC) used to evaluate customer profitability.",
  "A/B testing": "Controlled experiment where two variants are shown to users to measure which performs better.",
  "DACI": "Decision‑making framework: Driver, Approver, Contributors, Informed.",
  "RACI": "Responsibility assignment matrix: Responsible, Accountable, Consulted, Informed.",
  "SWOT": "Strategic analysis grid: Strengths, Weaknesses, Opportunities, Threats.",
  "Porter’s Five Forces": "Industry analysis tool: New entrants, Suppliers, Buyers, Substitutes, Rivalry.",
  "PESTEL": "Macro‑environmental scanning: Political, Economic, Social, Technological, Environmental, Legal.",
  "Value Proposition Canvas": "Maps Customer Profile (pains, gains) to Value Map (pain relievers, gain creators).",
  "North Star Metric": "The single metric that best captures the core value a product delivers to customers.",
  "Retention cohorts": "Method of grouping users by sign-up date to track activity over time.",

  // Products
  "Spotify": "Music streaming service known for personalisation and its freemium model.",
  "Duolingo": "Language learning app famous for gamification and aggressive A/B testing.",
  "Notion": "All‑in‑one productivity workspace for notes, databases, and wikis.",
  "Figma": "Collaborative interface design tool. Real‑time multiplayer and browser‑based.",
  "Calm": "Meditation and sleep app. Market leader in wellness with high-production stories.",
  "Airbnb": "Short‑term rental marketplace. Iconic case study for trust and marketplace dynamics.",
  "Uber Eats": "Food delivery platform. Complex three‑sided marketplace (eaters, restaurants, couriers).",
  "Slack": "Team communication hub using channels and huddles. Product‑led growth pioneer.",
  "Netflix": "Streaming video service. Expert at algorithms and experimentation.",
  "Headspace": "Meditation app with structured courses and distinctive illustration style.",
  "Zoom": "Video conferencing platform known for simplicity and reliability.",
  "DoorDash": "Food delivery leader in US with a strong subscriber program (DashPass).",
  "Google Maps": "Navigation and local discovery layer for over 1B users.",
  "Goodreads": "Social cataloguing for books. Retains a passionate but vocal community.",
  "Apple Health": "iOS health data aggregator. Collects steps, sleep, and heart rate data.",
  "WhatsApp": "Encrypted messaging app used by over 2B users globally.",
  "Twitter": "Microblogging network (now X) used for real-time news and public conversation.",
  "LinkedIn": "Professional network for jobs, content feed, and B2B advertising.",
  "Amazon": "Global e-commerce giant and cloud services provider.",
  "Google": "Search giant and suite of productivity tools (Docs, Gmail, etc).",
  "Meta": "Parent company of Facebook, Instagram, and WhatsApp.",

  // Outcomes
  "3 things I finally understand": "Personal breakthroughs after wrestling with a concept. Signals humility and mastery.",
  "a mistake I made": "Owning an error in application. Builds trust and makes the post relatable.",
  "a concept I applied": "Demonstrates that learning wasn’t passive and was used on a real product.",
  "a question I still have": "Ends with genuine curiosity to invite reader engagement.",
  "a template I created": "A reusable artifact (spreadsheet, Notion page) that readers can copy immediately.",
  "my cheat sheet": "Condensed reference guide (usually a one-page PDF) for quick recall.",
  "an experiment I designed": "An A/B test or research plan showing experimental rigour.",
  "a workshop I facilitated": "Author led a session to apply a framework, showing leadership.",

  // Formats / Purposes
  "Notion template": "Reusable database or dashboard duplicated into a user's own workspace.",
  "Google Sheets": "Spreadsheet with formulas, often used for calculators or trackers.",
  "PDF one-pager": "Single‑page visual summary. Best for framework quick reference.",
  "Miro board": "Collaborative whiteboard template for journey mapping or retros.",
  "Figma wireframe kit": "Reusable UI components helping PMs create quick low-fi prototypes.",
  "Trello board": "Kanban‑style template for simple project tracking.",
  "Confluence template": "Structured documentation page for team-internal PRDs or notes.",
  "Airtable base": "Relational database powerful for complex data relationships.",
  "OKR setting": "Guides teams through drafting and aligning Objectives and Key Results.",
  "RICE scoring calculator": "Automated spreadsheet outputting RICE scores and priority ranks.",
  "PRD outline": "Skeleton for a Product Requirements Document (problem, metrics, scope).",
  "user interview guide": "Script and question bank focused on customer discovery.",
  "launch checklist": "Go‑to‑market tasks from pre‑launch to post‑launch monitoring.",
  "post-mortem retrospective": "Blameless review of what happened and why.",
  "roadmap communication": "Visual template to present strategy to stakeholders clearly.",
  "competitive analysis": "Matrix comparing products on features, UX, and pricing.",

  // Angles
  "based on 3 failed quarters": "Implies learning from real failure, adding weight to the advice.",
  "after reading Inspired": "Signals that the resource was created while principles were fresh.",
  "from a mentor at Google": "Suggests insider knowledge from a top‑tier PM.",
  "tested with 3 stakeholders": "Validated with real colleagues, adding practicality.",
  "distilled from 5 real post-mortems": "Synthesised from actual project retrospectives.",
  "for remote teams": "Tailored to asynchronous, distributed work environments.",
  "with 5 competitor scores": "Includes benchmarking data making it more actionable.",

  // Domains & Pain Points
  "Dentist’s office": "Setting for physical service design case studies.",
  "Grocery store": "Supermarket environment. Common pain points: wayfinding and queues.",
  "Coffee shop": "Café environment. Pain points: accuracy and congestion.",
  "Gym": "Fitness centre. Pain points: equipment availability and cancellation.",
  "Hotel": "Hospitality setting. Pain points: check‑in speed and amenity clarity.",
  "Post office": "Postal service. Pain points: queue management and tracking.",
  "Airport": "Air travel hub. High-stress environment with security friction.",
  "Library": "Public lending institution. Pain points: overdue fines and wayfinding.",
  "Pharmacy": "Drugstore. Pain points: wait times and insurance confusion.",
  "Parking garage": "Vehicle facility. Pain points: payment friction and jams.",
  "Waiting time": "Idle period before service. Emotional cost: anxiety and boredom.",
  "Finding items": "Difficulty locating products. Causes: signage or inventory issues.",
  "Order accuracy": "Mistakes in delivery leading to customer frustration.",
  "Cancellation hassle": "Complex process to end a subscription (intentional friction).",
  "Check-in queue": "Long lines at reception, a key first-impression killer.",
  "Lost parcel": "Package undelivered with high emotional cost for user.",
  "Security anxiety": "Stress during airport screening (liquids, laptops, etc).",
  "Fine confusion": "Unclear overdue fees causing surprise charges.",

  // Methods & Artifacts
  "Journey map": "Visualisation of user steps, emotions, and touchpoints.",
  "Diary study": "Users log thoughts over days to uncover habits.",
  "5 Whys": "Root cause analysis by repeatedly asking “why”.",
  "Assumption mapping": "Prioritising belief-risks to test them first.",
  "Service blueprint": "Diagram of frontstage and backstage team processes.",
  "Root cause analysis": "Systematic investigation of a problem’s origin.",
  "JTBD interview": "Interview probing context and struggle rather than features.",
  "Usability test": "Observing users attempt tasks to identify confusion.",
  "SMS check-in": "Text notification to reduce perceived wait time.",
  "Store map in app": "Interactive layout to help shoppers navigate quickly.",
  "Digital ticket": "Mobile verification reducing printing and loss.",
  "One-click pause": "Instantly freeze membership without calling.",
  "Self-service kiosk": "Automated terminal to cut queues and workload.",
  "Tracking micro-updates": "Proactive alerts to reduce package anxiety.",
  "Fast-track prediction": "AI estimates for low-traffic times at security.",
  "Digital receipt": "Email record of returned items providing closure.",

  // Teardown features
  "Airbnb Instant Book": "Allows guests to book without host approval. Goal: higher conversion.",
  "Spotify Enhance": "Button that adds recommended songs to user playlists.",
  "Instagram Reels": "Short‑form vertical algorithmic video feed.",
  "Gmail tabs": "Auto‑categorisation of emails to reduce primary inbox clutter.",
  "Slack huddles": "Lightweight audio conversations for quick channel syncs.",
  "DoorDash fees": "Service and delivery fees displayed at checkout.",
  "Goodreads ‘Want to Read’": "Virtual shelf for saving books for future reading.",
  "Zoom backgrounds": "Virtual backdrops preserving caller privacy.",
  "Notion templates": "Pre‑made page layouts in the Notion ecosystem.",

  // New Features
  "Quiet mode": "Prioritises peaceful routes (fewer turns, less noise) over speed.",
  "Bedtime mode": "Timer with sleep‑friendly UI and automatic fade-out.",
  "Group reading tracker": "Shared progress bar and discussion prompts for book clubs.",
  "Sleep debt dashboard": "Visualisation of missed vs. caught‑up sleep segments.",
  "AI lecture summariser": "Automated transcription and key‑point extraction from audio.",
  "Large-text mode": "System‑wide font scaling and high‑contrast enforcement.",
  "No-spoiler filter": "Toggle to hide plot descriptions and synopses.",
  "Micro-meditation": "60‑second guided exercises embedded in work apps.",

  // Prototype Artifacts
  "Low-fi wireframe": "Hand‑drawn or basic digital sketch focusing on flow.",
  "User story + mockup": "Narrative (As a... I want...) paired with a visual sketch.",
  "Figma prototype": "Clickable high‑fidelity interactive model.",
  "Success metrics": "Proposed KPIs to measure feature activation and impact.",
  "Paper prototype": "Physical paper sketches for fast user-testing.",
  "Before/after flow": "Comparison highlighting redesign changes.",
  "Toggle design": "Specification of a switch control's states and behaviour.",
  "Inline prompt": "Contextual UI element appearing at the exact moment of need.",

  // Career Situations
  "Mock interview": "Simulated practice for product sense or execution interviews.",
  "Job description analysis": "Reviewing postings to identify skill patterns and trends.",
  "First 90 days": "Critical onboarding period for a new product role.",
  "Networking": "Reaching out to PMs for advice or referrals.",
  "Portfolio building": "Creating artifacts like PRDs to demonstrate skills to hirers.",
  "Career ladder": "Evaluating progression from APM to Senior roles.",
  "Common PM problem": "Recurring challenges like stakeholder or priority conflicts.",
  "Estimation questions": "Interview tests for structured thinking and uncertainty comfort.",
  "Required PM skills": "Decoding vague competencies like 'strategic thinking'.",
  "Onboarding strategy": "Plan to learn product, team, and domain quickly.",
  "Finding a sponsor": "Identifying an advocate who campaigns for your promotions.",
  "Fake PRD": "Hypothetical requirement document showcasing writing skills.",
  "APM → PM → Senior": "The typical career progression path in product management.",
  "Executive feature request": "Handling unplanned features demanded by leadership.",
  "Post-mortem": "Reflective analysis of a career mistake or failure.",
  "Spreadsheet audit": "Structured data collection, e.g., skill frequency in job ads.",
  "Personal retrospective": "Honest diary-style reflection on a period of work.",
  "Conversation summary": "Key takeaways from a networking session.",
  "Template + reflection": "Reusable resource plus commentary on its use.",
  "Self-assessment": "Scoring oneself against a competency framework.",
  "Problem-solution story": "Narrative arc used in PM interviews/storytelling.",
  "3 mistakes": "Concrete errors to avoid in a specific career scenario.",
  "What “influence” really means": "Decoding trust-building and stakeholder mapping.",
  "What I wish I’d known": "Lessons learned late about networking or help-seeking.",
  "1 unexpected ask": "A surprising request that opened a career door.",
  "Before/after": "Comparison showing growth in approach over time.",
  "My weakest spoke": "Honest critique of one's lowest framework score.",
  "How I said “no”": "Tactic for declining requests while managing stakeholders."
};
